server.port=8081
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=restaurant_dbb;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=\u044b\u0444
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/
