# ========== SERVER ==========
server.port=8081
server.servlet.context-path=/restaurant_war_exploded
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# ========== SQL SERVER ==========
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=restaurant_dbb;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# ========== HIBERNATE (JPA) ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ========== MVC ==========
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ========== EMAIL ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gaukharsaduakas05@gmail.com
spring.mail.password=hcewfaaisqnpqqcq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# ========== LOGGING ==========
logging.level.root=INFO
logging.level.com.gauhar.restaurant=DEBUG
logging.level.org.springframework.security=DEBUG

